import {
  InspectionStatus,
  InspectionStepId,
  FuelType,
  TransmissionType,
  Condition,
  YesNoNA,
  UserRole,
  type InspectionLead,
  type InspectionSession,
  type User,
} from '../features/inspection/types';

// ─── Mock User ────────────────────────────────────────────────────────────────

export const mockUser: User = {
  id: 'cj_001',
  name: 'Rahul Sharma',
  phone: '9876543210',
  role: UserRole.CJ,
  employeeId: 'EMP4521',
  zone: 'Delhi NCR',
  profileImage: undefined,
};

// ─── Mock Inspections ─────────────────────────────────────────────────────────

export const mockInspections: InspectionLead[] = [
  {
    id: 'lead_001',
    appointmentId: '35821299199',
    scheduledAt: '2026-04-06T10:30:00.000Z',
    status: InspectionStatus.InProgress,
    car: {
      make: 'Maruti Suzuki',
      model: 'Swift',
      variant: 'ZXi Plus',
      year: 2021,
      color: 'Pearl Arctic White',
      fuelType: FuelType.Petrol,
      transmission: TransmissionType.Manual,
      kmDriven: 42500,
      registrationNumber: 'DL 3C AB 4521',
      registrationState: 'Delhi',
      ownerCount: 1,
      insuranceValidity: '2026-12-31',
    },
    owner: {
      id: 'owner_001',
      name: 'Ankit Verma',
      phone: '9988776655',
      address: 'B-42, Sector 15, Dwarka',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110075',
    },
    assignedCJId: 'cj_001',
    location: {
      latitude: 28.5930,
      longitude: 77.0465,
      address: 'B-42, Sector 15, Dwarka, New Delhi - 110075',
    },
  },
  {
    id: 'lead_002',
    appointmentId: '35821287344',
    scheduledAt: '2026-04-06T13:00:00.000Z',
    status: InspectionStatus.Pending,
    car: {
      make: 'Hyundai',
      model: 'Creta',
      variant: 'SX(O)',
      year: 2020,
      color: 'Typhoon Silver',
      fuelType: FuelType.Diesel,
      transmission: TransmissionType.Automatic,
      kmDriven: 67800,
      registrationNumber: 'HR 26 BX 9910',
      registrationState: 'Haryana',
      ownerCount: 2,
      insuranceValidity: '2026-08-15',
    },
    owner: {
      id: 'owner_002',
      name: 'Pooja Singh',
      phone: '9871234560',
      address: 'H. No 112, Sector 21, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122001',
    },
    assignedCJId: 'cj_001',
    location: {
      latitude: 28.4595,
      longitude: 77.0266,
      address: 'H. No 112, Sector 21, Gurugram, Haryana - 122001',
    },
  },
  {
    id: 'lead_003',
    appointmentId: '35821250011',
    scheduledAt: '2026-04-05T11:00:00.000Z',
    status: InspectionStatus.Completed,
    car: {
      make: 'Honda',
      model: 'City',
      variant: 'VX CVT',
      year: 2019,
      color: 'Lunar Silver Metallic',
      fuelType: FuelType.Petrol,
      transmission: TransmissionType.CVT,
      kmDriven: 55200,
      registrationNumber: 'UP 16 AT 1122',
      registrationState: 'Uttar Pradesh',
      ownerCount: 1,
      insuranceValidity: '2025-11-30',
    },
    owner: {
      id: 'owner_003',
      name: 'Suresh Gupta',
      phone: '9977665544',
      address: '45, Indirapuram, Noida Extension',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201012',
    },
    assignedCJId: 'cj_001',
    location: {
      latitude: 28.6417,
      longitude: 77.3756,
      address: '45, Indirapuram, Noida Extension - 201012',
    },
  },
  {
    id: 'lead_004',
    appointmentId: '35821301876',
    scheduledAt: '2026-04-07T09:30:00.000Z',
    status: InspectionStatus.Pending,
    car: {
      make: 'Tata',
      model: 'Nexon EV',
      variant: 'Max XZ+',
      year: 2022,
      color: 'Intensi-Teal',
      fuelType: FuelType.Electric,
      transmission: TransmissionType.Automatic,
      kmDriven: 28000,
      registrationNumber: 'MH 02 QQ 5678',
      registrationState: 'Maharashtra',
      ownerCount: 1,
      insuranceValidity: '2027-03-20',
    },
    owner: {
      id: 'owner_004',
      name: 'Meera Patil',
      phone: '9812345678',
      address: 'Flat 3B, Sky Residency, Andheri West',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400058',
    },
    assignedCJId: 'cj_001',
    location: {
      latitude: 19.1136,
      longitude: 72.8697,
      address: 'Flat 3B, Sky Residency, Andheri West, Mumbai - 400058',
    },
  },
];

// ─── Empty Inspection Session Factory ─────────────────────────────────────────

export const createEmptySession = (lead: InspectionLead): InspectionSession => ({
  leadId: lead.id,
  appointmentId: lead.appointmentId,
  startedAt: new Date().toISOString(),
  status: InspectionStatus.InProgress,
  steps: [
    { id: InspectionStepId.BasicVerification, title: 'Car Details', icon: '📋', isCompleted: false, isLocked: false },
    { id: InspectionStepId.Exterior, title: 'Engine + Transmission', icon: '⚙️', isCompleted: false, isLocked: false },
    { id: InspectionStepId.Interior, title: 'Air Conditioning', icon: '❄️', isCompleted: false, isLocked: false },
    { id: InspectionStepId.Engine, title: 'Steering + Brakes', icon: '🛞', isCompleted: false, isLocked: false },
    { id: InspectionStepId.Documents, title: 'Electricals + Interiors', icon: '💡', isCompleted: false, isLocked: false },
    { id: InspectionStepId.Media, title: 'Exterior + Tyres', icon: '🚙', isCompleted: false, isLocked: false },
  ],
  formData: {
    basicVerification: {},
    exterior: {},
    interior: {},
    engine: {},
    documents: {},
    media: {
      additionalImages: [],
      exteriorTyreParts: {},
      engineComponentPhotos: {},
      documentPhotoDetails: {},
    },
  },
});
